
services:
  db:
    image: postgres:16-alpine
    container_name: bank_postgres
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
      POSTGRES_DB: bank_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bank_user -d bank_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: bank_api
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://db:5432/bank_db
      - DB_USERNAME=bank_user
      - DB_PASSWORD=bank_password
      - JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

volumes:
  postgres_data:
